# -*- coding: utf-8 -*-
"""Sum of Subset (Column Foramtting).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v51cBSgkZXMVdWoPeLzx1duxizBjHoj2
"""

import pandas as pd

df1 = pd.read_excel('F:/ML IPYNB/financial-data-parser/data/sample/Customer_Ledger_Entries_FULL.xlsx')
df2 = pd.read_excel('F:/ML IPYNB/financial-data-parser/data/sample/KH_Bank.xlsx')

df1.head()

df2.head()

print(df1['Document No.'].count())
print(df1['Amount'].count())

df1_final = df1[['Document No.','Amount']]

#apply unique identifer
df1_final['Document No.'] = (
    df1_final.groupby('Document No.').cumcount() + 1
).astype(str).radd(df1_final['Document No.'] + "_")

df1_final['Document No.'].value_counts()

df1_final.sample(10)

df1_final['Amount'].head()

df2['Statement.Entry.Amount.Value'].value_counts()

target = df2[['Statement.Entry.Amount.Value']]

df1_final.sample(5)

target['Statement.Entry.Amount.Value'] = target['Statement.Entry.Amount.Value'].apply(lambda x: f"{x:.2f}")

target['Statement.Entry.Amount.Value'].count()

df1_final.head()

# df1_final.to_csv("ledger.csv", index=False)
# print("✅ df1_final saved to df1_final.csv")

target.head()

# target.to_csv("target.csv", index=False)
# print("✅ target saved to target.csv")

amount_list = list(target['Statement.Entry.Amount.Value'])
amount_list

my_dict = dict(zip(df1_final['Document No.'], df1['Amount']))
my_dict

ledger_dict = my_dict
del my_dict
ledger_dict

target_amount_column = amount_list
del amount_list
target_amount_column
# after that i save both into speartae csv file with target column in separate csv and ledger in separate